### ISSUE TITLE
Ask questions

### ISSUE THREAD

**Issue by dpzhao1** [PrabhatIn/HoneyTop90#1]
Hello professor, your article is very well written, but I have a few questions, and I would like to ask you, thank you very much. 
I found out that this hexamorph is not continuous? do not know why? 
Meanwhile, I can't calculate the stiffness result via the shape-function and the strain-matrix？don't know why?
function Ke=lk
E0=1;nu=0.3;h=1;a=(3)^(1/2)/2;b=1;
D=E0/(1-nu^2)*[1 nu 0;nu 1 0;0 0 (1-nu)/2];%D矩阵
syms x y;
% x=cos((2*i-1)*pi/6);
% y=sin((2*i-1)*pi/6);
   N1=((-x+sqrt(3)*y-sqrt(3))*(2*x+sqrt(3))*(x+sqrt(3)*y+sqrt(3))*(-x+sqrt(3)*y+sqrt(3)))/(18*(x^2+y^2-3));
   N2=((2*x+sqrt(3))*(x+sqrt(3)*y+sqrt(3))*(-x+sqrt(3)*y+sqrt(3))*(2*x-sqrt(3)))/(18*(x^2+y^2-3));
   N3=-((x+sqrt(3)*y+sqrt(3))*(-x+sqrt(3)*y+sqrt(3))*(2*x-sqrt(3))*(x+sqrt(3)*y-sqrt(3)))/(18*(x^2+y^2-3));
   N4=((-x+sqrt(3)*y+sqrt(3))*(2*x-sqrt(3))*(x+sqrt(3)*y-sqrt(3))*(-x+sqrt(3)*y-sqrt(3)))/(18*(x^2+y^2-3));
   N5=((2*x-sqrt(3))*(x+sqrt(3)*y-sqrt(3))*(-x+sqrt(3)*y-sqrt(3))*(2*x+sqrt(3)))/(18*(x^2+y^2-3));
   N6=-((x+sqrt(3)*y-sqrt(3))*(-x+sqrt(3)*y-sqrt(3))*(2*x+sqrt(3))*(x+sqrt(3)*y+sqrt(3)))/(18*(x^2+y^2-3));
   B=[diff(N1,x) 0 diff(N2,x) 0 diff(N3,x) 0 diff(N4,x) 0 diff(N5,x) 0 diff(N6,x) 0
      0 diff(N1,y) 0 diff(N2,y) 0 diff(N3,y) 0 diff(N4,y) 0 diff(N5,y) 0 diff(N6,y)
      diff(N1,y) diff(N1,x) diff(N2,y) diff(N2,x) diff(N3,y) diff(N3,x) diff(N4,y) diff(N4,x) diff(N5,y) diff(N5,x) diff(N6,y) diff(N6,x)]; %B矩阵
   Ke=double(int(int((B'*D*B*h),x,-a,a), y,-b,b)) 
end

**Comment by PrabhatIn** [comment]
Please use HoneyMesher.m function: if you wish to generate only honeycomb tessellation.  For stiffness matrix, you can use numerical integration instead.

**Comment by dpzhao1** [comment]
Thank you very much for your reply, because I want to consider using this method to calculate the stress and try it later. thanks...
