### ISSUE TITLE
Question about B matrix data corresponding to the program

### ISSUE THREAD

**Issue by DeiYang** [PrabhatIn/HoneyTop90#2]
Hello, professor, I also used shape function to calculate stress, and found that the hexagon side length a=1 in your paper was derived, and the side length in the program was calculated by 1/ (3^1/2). Could you please provide the B matrix data corresponding to the program? thank you

**Comment by dpzhao1** [comment]
Yes, Could you please provide the B matrix data corresponding to the program? thank you. I calculate the  function s1=s2=s4=s5=0.1667, s3=s6=-0.1667;
B=[ 3^(1/2)/6  0, 3^(1/2)/3  0, 3^(1/2)/6  0 -3^(1/2)/6  0 -3^(1/2)/3  0 -3^(1/2)/6  0]
 0 1/2   0   0   0 -1/2  0  -1/2  0   0  0 1/2;
1/2 3^(1/2)/6  0 3^(1/2)/3 -1/2 3^(1/2)/6 -1/2  -3^(1/2)/6  0 -3^(1/2)/3 1/2 -3^(1/2)/6];
However,the calculated stress result is wrong.

**Comment by PrabhatIn** [comment]
> Hello, professor, I also used shape function to calculate stress, and found that the hexagon side length a=1 in your paper was derived, and the side length in the program was calculated by 1/ (3^1/2). Could you please provide the B matrix data corresponding to the program? thank you

Please see the published version (https://link.springer.com/article/10.1007/s11081-022-09715-6), attached supplementary codes there and those here

Regarding B matrix calculation, please follow the integration scheme given in Appendix D of the paper (https://link.springer.com/article/10.1007/s11081-022-09715-6). 

thanks.

**Comment by PrabhatIn** [comment]
> Yes, Could you please provide the B matrix data corresponding to the program? thank you. I calculate the function s1=s2=s4=s5=0.1667, s3=s6=-0.1667; B=[ 3^(1/2)/6 0, 3^(1/2)/3 0, 3^(1/2)/6 0 -3^(1/2)/6 0 -3^(1/2)/3 0 -3^(1/2)/6 0] 0 1/2 0 0 0 -1/2 0 -1/2 0 0 0 1/2; 1/2 3^(1/2)/6 0 3^(1/2)/3 -1/2 3^(1/2)/6 -1/2 -3^(1/2)/6 0 -3^(1/2)/3 1/2 -3^(1/2)/6]; However,the calculated stress result is wrong.

Please follow the integration scheme given in Appendix D of the paper (https://link.springer.com/article/10.1007/s11081-022-09715-6). You can use a (edge length) = 1 for all calculations.
